In [1]:
import tensorflow as tf
import numpy as np

In [2]:
def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    dataset = tf.data.Dataset.from_tensor_slices(series)
    dataset = dataset.window(window_size+1, shift=1, drop_remainder=True)
    dataset = dataset.flat_map(lambda window:window.batch(window_size+1))
    dataset = dataset.shuffle(shuffle_buffer).map(lambda window: (window[:-1], window[-1]))
    dataset = dataset.batch(batch_size).prefetch(1)
    return dataset

In [3]:
window_size = 4
batch_size = 2
shuffle_buffer = 5

In [5]:
series = np.array([0,1,2,3,4,5,6,7,8,9])
for X, y in windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    print(X.numpy(),y.numpy())

[[0 1 2 3]
 [4 5 6 7]] [4 8]
[[1 2 3 4]
 [2 3 4 5]] [5 6]
[[5 6 7 8]
 [3 4 5 6]] [9 7]
